# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-07 06:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flatpages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('slug', models.SlugField(max_length=32)),
                ('seq', models.PositiveIntegerField(default=0, unique=True, verbose_name='Order')),
                ('url', models.URLField(blank=True, null=True, verbose_name='URL')),
                ('flatpage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flatpages.FlatPage', verbose_name='Page')),
            ],
        ),
    ]
