# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('notes', models.TextField()),
                ('image', models.ImageField(upload_to='thumbnails/')),
                ('data', models.FileField(upload_to='data/')),
                ('url', models.URLField()),
            ],
        ),
    ]
