# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 14:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Published'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asset',
            name='version',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='notes',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
