# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 19:03
from __future__ import unicode_literals

from django.db import migrations, models
import taggit_autosuggest.managers


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_auto_20170103_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='tags',
            field=taggit_autosuggest.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
