# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_auto_20170103_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='num_votes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
