# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0009_profile_follows'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='slug',
            field=models.SlugField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='component',
            name='slug',
            field=models.SlugField(max_length=32, unique=True),
        ),
    ]
