# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 06:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0011_auto_20170105_0616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='id',
        ),
        migrations.RemoveField(
            model_name='component',
            name='id',
        ),
        migrations.AddField(
            model_name='application',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='slug',
            field=models.SlugField(max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='asset',
            name='version',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='component',
            name='slug',
            field=models.SlugField(max_length=32, primary_key=True, serialize=False),
        ),
    ]
