# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0012_auto_20170105_0651'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='install_instructions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='component',
            name='upload_instructions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
