# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 08:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0013_auto_20170105_0749'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='creation_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Originally created'),
        ),
        migrations.AddField(
            model_name='asset',
            name='original_author',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
