# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-05 15:54
from __future__ import unicode_literals

from django.db import migrations
import versionfield


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0014_auto_20170105_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='version',
            field=versionfield.VersionField(blank=True, null=True),
        ),
    ]
