# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-05 17:12
from __future__ import unicode_literals

from django.db import migrations
import versionfield


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0015_auto_20170105_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='app_version_max',
            field=versionfield.VersionField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='app_version_min',
            field=versionfield.VersionField(blank=True, null=True),
        ),
    ]
