# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-08 07:44
from __future__ import unicode_literals

import assets.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0017_auto_20170105_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='thumbnailer_name',
            field=models.CharField(blank=True, choices=[(b'assets.thumbnailers.ImageThumbnailer', b'assets.thumbnailers.ImageThumbnailer')], default=None, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=assets.models.get_logo_path),
        ),
        migrations.AlterField(
            model_name='asset',
            name='data',
            field=models.FileField(upload_to=assets.models.get_data_path, verbose_name='data file'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=assets.models.get_thumbnail_path, verbose_name='thumbnail'),
        ),
    ]
