# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-08 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0018_auto_20170108_0744'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='thumbnail_mandatory',
            field=models.BooleanField(default=False, verbose_name='Thumbnail is mandatory'),
        ),
        migrations.AlterField(
            model_name='component',
            name='thumbnailer_name',
            field=models.CharField(blank=True, choices=[(b'assets.thumbnailers.ImageThumbnailer', b'Image file thumbnailer'), (b'assets.thumbnailers.KritaPresetThumbnailer', b'Krita preset thumbnailer'), (b'assets.thumbnailers.KritaBundleThumbnailer', b'Krita resource bundle thumbnailer')], default=None, max_length=64, null=True),
        ),
    ]
