# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 18:06
from __future__ import unicode_literals

import assets.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0020_component_file_masks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'verbose_name': 'application', 'verbose_name_plural': 'applications'},
        ),
        migrations.AlterModelOptions(
            name='asset',
            options={'verbose_name': 'asset', 'verbose_name_plural': 'assets'},
        ),
        migrations.AlterModelOptions(
            name='component',
            options={'verbose_name': 'component', 'verbose_name_plural': 'components'},
        ),
        migrations.AlterModelOptions(
            name='license',
            options={'verbose_name': 'license', 'verbose_name_plural': 'licenses'},
        ),
        migrations.AddField(
            model_name='profile',
            name='enable_api',
            field=models.BooleanField(default=False, verbose_name='Enable API'),
        ),
        migrations.AlterField(
            model_name='application',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=assets.models.get_logo_path, verbose_name='application logo'),
        ),
        migrations.AlterField(
            model_name='application',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='notes'),
        ),
        migrations.AlterField(
            model_name='application',
            name='notes_en',
            field=models.TextField(blank=True, null=True, verbose_name='notes'),
        ),
        migrations.AlterField(
            model_name='application',
            name='notes_ru',
            field=models.TextField(blank=True, null=True, verbose_name='notes'),
        ),
        migrations.AlterField(
            model_name='application',
            name='title',
            field=models.CharField(max_length=255, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='application',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='application',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='application',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='component',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.Application', verbose_name='application'),
        ),
        migrations.AlterField(
            model_name='component',
            name='file_masks',
            field=models.CharField(default='*', help_text='space-separated list of file masks, e.g. *.jpg', max_length=64, verbose_name='Allowed file masks'),
        ),
        migrations.AlterField(
            model_name='component',
            name='install_instructions',
            field=models.TextField(blank=True, null=True, verbose_name='Installation instructions'),
        ),
        migrations.AlterField(
            model_name='component',
            name='install_instructions_en',
            field=models.TextField(blank=True, null=True, verbose_name='Installation instructions'),
        ),
        migrations.AlterField(
            model_name='component',
            name='install_instructions_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Installation instructions'),
        ),
        migrations.AlterField(
            model_name='component',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='notes'),
        ),
        migrations.AlterField(
            model_name='component',
            name='notes_en',
            field=models.TextField(blank=True, null=True, verbose_name='notes'),
        ),
        migrations.AlterField(
            model_name='component',
            name='notes_ru',
            field=models.TextField(blank=True, null=True, verbose_name='notes'),
        ),
        migrations.AlterField(
            model_name='component',
            name='thumbnailer_name',
            field=models.CharField(blank=True, choices=[(b'assets.thumbnailers.ImageThumbnailer', b'Image file thumbnailer'), (b'assets.thumbnailers.KritaPresetThumbnailer', b'Krita preset thumbnailer'), (b'assets.thumbnailers.KritaBundleThumbnailer', b'Krita resource bundle thumbnailer')], default=None, max_length=64, null=True, verbose_name='automatic thumbnail creation'),
        ),
        migrations.AlterField(
            model_name='component',
            name='title',
            field=models.CharField(max_length=255, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='component',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='component',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='component',
            name='upload_instructions',
            field=models.TextField(blank=True, null=True, verbose_name='Upload instructions'),
        ),
        migrations.AlterField(
            model_name='component',
            name='upload_instructions_en',
            field=models.TextField(blank=True, null=True, verbose_name='Upload instructions'),
        ),
        migrations.AlterField(
            model_name='component',
            name='upload_instructions_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Upload instructions'),
        ),
        migrations.AlterField(
            model_name='license',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='license',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Legal text'),
        ),
        migrations.AlterField(
            model_name='license',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
    ]
