# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0021_auto_20170118_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='max_thumbnail_size',
            field=models.IntegerField(default=300, verbose_name='Maximum thumbnail size'),
        ),
    ]
