# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0023_auto_20170122_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_assets',
            field=models.BooleanField(default=False, verbose_name='Send email notifications about new assets in my feed'),
        ),
        migrations.AddField(
            model_name='profile',
            name='email_comments',
            field=models.BooleanField(default=False, verbose_name='Send email notifications about comments for my assets'),
        ),
        migrations.AddField(
            model_name='profile',
            name='email_mention',
            field=models.BooleanField(default=False, verbose_name='Send email notifications about me being mentioned'),
        ),
    ]
